require('plugins')
require('telescope_config')
require('trouble_setup')
require('telekasten_config')
require('color_themes')
require('lan_server_setup')
require('snippets_setup')
-- require('jupyter_setup')
require('gitsigns_setup')
require('mappings')
require('toggleterm_config')
